 setTimeout(function(){
                  document.getElementById('TimeCounter').innerHTML='10';
                  setTimeout(function(){
                    document.getElementById('TimeCounter').innerHTML='9';
                    setTimeout(function(){
                       document.getElementById('TimeCounter').innerHTML='8';
                       setTimeout(function(){
                          document.getElementById('TimeCounter').innerHTML='7';
                          setTimeout(function(){
                              document.getElementById('TimeCounter').innerHTML='6';
                              setTimeout(function(){
                                  document.getElementById('TimeCounter').innerHTML='5';
                                  setTimeout(function(){
                                      document.getElementById('TimeCounter').innerHTML='4';
                                      setTimeout(function(){
                                         document.getElementById('TimeCounter').innerHTML='3';
                                         setTimeout(function(){
                                             document.getElementById('TimeCounter').innerHTML='2';
                                             setTimeout(function(){
                                                 document.getElementById('TimeCounter').innerHTML='1';
                                                 setTimeout(function(){
                                                    document.getElementById('TimeCounter').innerHTML='HAPPY INDEPENDENCE  DAY'; 
                                                    },1000)
                                                 },1000)
                                             },1000)
                                        },1000)
                                    },1000)
                               },1000)
                            },1000)
                        },1000)
                   },1000)
              },1000)
            })